Added second parameter "count" to deleteTemplate()
bastianraschke/pyfingerprint pull request #18
Opened 2017-04-16 16:14 UTC by philippmeisberger

Allow to set the number of templates that should be deleted

2017-04-16 17:03 UTC, bastianraschke requested changes

2017-04-16 17:03 UTC, bastianraschke commented on src/files/pyfingerprint/pyfingerprint.py
> +    def deleteTemplate(self, positionNumber, count = 1):
We should validate the argument:
N = getStorageCapacity() - positionNumber - 1 (if N is not >= 1 we reject the call)

2017-04-17 11:03 UTC, philippmeisberger commented on src/files/pyfingerprint/pyfingerprint.py
> +    def deleteTemplate(self, positionNumber, count = 1):
Sensor already validates this and gives an error if passing wrong arguments

2017-04-22 21:35 UTC, bastianraschke commented on src/files/pyfingerprint/pyfingerprint.py
> +    def deleteTemplate(self, positionNumber, count = 1):
It is always better to validate it to avoid possible malfunction of the sensor hardware.

2017-04-22 21:36 UTC, bastianraschke approved these changes

2017-04-22 21:37 UTC, merged