Add option to enable debug messages
bastianraschke/pyfingerprint pull request #29
Opened 2018-01-17 14:49 UTC by cyberjacob

2018-01-20 09:38 UTC, philippmeisberger commented
The built-in python `logging` module could also be used for this.

2018-01-25 18:33 UTC, bastianraschke requested changes
Yeah build in Python logging module would be quite better

2018-01-25 18:33 UTC, bastianraschke commented on src/files/pyfingerprint/pyfingerprint.py
> +        self.debug = debug
why public?

2018-01-25 18:33 UTC, bastianraschke commented on src/files/pyfingerprint/pyfingerprint.py
> +            if self.debug:
Please use braces and explicit boolean expression (to be consistent with our code style)

2018-01-25 18:33 UTC, bastianraschke commented on src/files/pyfingerprint/pyfingerprint.py
> +                    if self.debug:
Please use braces and explicit boolean expression (to be consistent with our code style)

2018-01-25 18:33 UTC, bastianraschke commented on src/files/pyfingerprint/pyfingerprint.py
> +                        print("Invalid packet recieved: "+str(receivedPacketData))
typo + single marks please

2018-01-25 18:33 UTC, bastianraschke commented on src/files/pyfingerprint/pyfingerprint.py
> +        #TODO: Make seperate functions for each of the parameters, would be more useful.
We implemented it according to the spec document that contained these call. It is the counterpart of the "getSystemParameters" call that gives us the full information without choice. Please remove TODO.

2018-11-16 20:06 UTC, bastianraschke commented
We closed the PR because of absence of @cyberjacob. The feature itself is nice, but without adjustments we don't want to merge it.

2018-11-16 20:06 UTC, closed without merging